model_name: "sberbank-ai/rugpt3large_based_on_gpt2"
generate_params:
  num_beams: 5               # Количество лучей для beam search. Увеличивает число возможных путей генерации текста, выбирая наиболее вероятные.
  max_length: 300            # Максимальная длина генерируемого текста в токенах.
  temperature: 0.8           # Параметр, влияющий на случайность генерации. Фантазия
  top_k: 100                 # Параметр, ограничивающий выбор токенов при генерации только k наиболее вероятными.
  top_p: 0.95                # Определяет вероятность, которую необходимо покрыть выбором токенов. Например, top_p=0.95 означает, что модель будет выбирать среди токенов, суммарная вероятность которых составляет 95%.
  no_repeat_ngram_size: 3    # 
  repetition_penalty: 1.1    # Параметр, который добавляет штраф за повторяющиеся слова и фразы.
  length_penalty: 1.2        # Параметр, влияющий на предпочтение модели генерировать более длинные или более короткие фразы.
  do_sample: true            # Включает вероятностную выборку для создания более разнообразного текста.
  early_stopping: true       # Заставит модель остановиться на завершении предложения, если оно встречается до достижения max_length